services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql@16/data
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder  # Specify the target stage for the backend
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD: password
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder  # Specify the target stage for the frontend
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn start && yarn storybook"
    ports:
      - "4000:4000"
    depends_on:
      - backend
    environment:
      POSTGRES_PASSWORD: password
    restart: always
